baseURL = 'https://nshahpazov.github.io/'
languageCode = 'en-us'
title = "Nikola Shahpazov"
theme = 'ananke'
sectionPagesMenu = 'main'
[services.disqus]
  shortname = 'nshahpazov'
[params]
  commentoEnable = true
  customCSS = ["css/custom.css"]


# background_color_class = "bg-red"
[languages]
  [languages.en]
    weight = 1
    contentDir = "content/en"
  [languages.bg]
    weight = 2
    contentDir = "content/bg"